/**
 * Default tasks for each EB-1A process phase
 * Based on VISAFLOW CONTEXT.md workflow
 */

export interface DefaultTask {
  title: string;
  description: string;
  phase: 'ELIGIBILITY' | 'EVIDENCE' | 'LETTERS' | 'PETITION' | 'FILING';
  order: number;
  dependsOn?: number[]; // Indexes of tasks this depends on
}

export const DEFAULT_TASKS: DefaultTask[] = [
  // ============================================
  // PHASE 1: ELIGIBILITY (Tasks 0-19) - 20 tarefas
  // ============================================
  
  // Auto-Avaliação Inicial (5 tarefas)
  {
    title: 'Avaliar os 10 Critérios EB-1A Individualmente',
    description: 'Revisar cada um dos 10 critérios EB-1A e avaliar sua capacidade de comprovar cada um. Você precisa de pelo menos 3 critérios sólidos.',
    phase: 'ELIGIBILITY',
    order: 0,
  },
  {
    title: 'Fazer Inventário de Evidências Existentes',
    description: 'Listar todas as evidências que você já possui: prêmios, publicações, cartas, mídia, certificados, etc. Organizar por critério.',
    phase: 'ELIGIBILITY',
    order: 1,
    dependsOn: [0],
  },
  {
    title: 'Identificar Gaps de Evidências',
    description: 'Comparar evidências existentes com requisitos de cada critério. Identificar o que falta para fortalecer cada critério.',
    phase: 'ELIGIBILITY',
    order: 2,
    dependsOn: [1],
  },
  {
    title: 'Definir Área de Expertise Específica',
    description: 'Definir claramente sua área de habilidade extraordinária. Deve ser específica o suficiente para demonstrar expertise única.',
    phase: 'ELIGIBILITY',
    order: 3,
    dependsOn: [0],
  },
  {
    title: 'Pesquisar Cases Similares Aprovados',
    description: 'Estudar casos EB-1A aprovados na sua área. Identificar padrões de sucesso e estratégias que funcionaram.',
    phase: 'ELIGIBILITY',
    order: 4,
    dependsOn: [0],
  },

  // Planejamento Estratégico (5 tarefas)
  {
    title: 'Escolher 3-5 Critérios Mais Fortes',
    description: 'Selecionar os critérios onde você tem evidências mais sólidas. Focar em qualidade, não quantidade. Mínimo 3 critérios.',
    phase: 'ELIGIBILITY',
    order: 5,
    dependsOn: [1, 2],
  },
  {
    title: 'Priorizar Critérios por Força de Evidências',
    description: 'Ordenar critérios escolhidos por força de evidências. O mais forte primeiro, para usar como âncora da petição.',
    phase: 'ELIGIBILITY',
    order: 6,
    dependsOn: [5],
  },
  {
    title: 'Definir Estratégia de Comparable Evidence',
    description: 'Se algum critério não atende completamente, planejar uso de "comparable evidence" para demonstrar equivalência.',
    phase: 'ELIGIBILITY',
    order: 7,
    dependsOn: [5],
  },
  {
    title: 'Estimar Custo Total do Processo',
    description: 'Calcular custos: taxas USCIS ($700 I-140 + $2,500 premium), traduções, impressão, envio, exames médicos, etc.',
    phase: 'ELIGIBILITY',
    order: 8,
    dependsOn: [5],
  },
  {
    title: 'Criar Timeline Realista (3-6 meses)',
    description: 'Estimar tempo necessário para cada fase e definir datas alvo. Típico: 3-6 meses de preparação antes do filing.',
    phase: 'ELIGIBILITY',
    order: 9,
    dependsOn: [5, 6],
  },

  // Preparação Legal (5 tarefas)
  {
    title: 'Ler Policy Manual do USCIS',
    description: 'Estudar o Adjudicator\'s Field Manual e Policy Manual do USCIS sobre EB-1A. Entender requisitos legais específicos.',
    phase: 'ELIGIBILITY',
    order: 10,
    dependsOn: [0],
  },
  {
    title: 'Estudar Template de RFE',
    description: 'Revisar exemplos de Request for Evidence (RFE) para EB-1A. Entender pontos fracos comuns que causam RFEs.',
    phase: 'ELIGIBILITY',
    order: 11,
    dependsOn: [10],
  },
  {
    title: 'Entender Estrutura de 4 Subseções',
    description: 'Aprender estrutura obrigatória: Proof of Recipient, Proof of Excellence, Proof of Requirements, Proof of Recognition.',
    phase: 'ELIGIBILITY',
    order: 12,
    dependsOn: [10],
  },
  {
    title: 'Pesquisar Escritórios de Advocacia (se necessário)',
    description: 'Se decidir usar advogado, pesquisar escritórios especializados em EB-1A. Comparar custos e experiência.',
    phase: 'ELIGIBILITY',
    order: 13,
    dependsOn: [8],
  },
  {
    title: 'Decidir: DIY vs. Advogado',
    description: 'Tomar decisão final sobre fazer processo sozinho (DIY) ou contratar advogado. Considerar custo vs. risco.',
    phase: 'ELIGIBILITY',
    order: 14,
    dependsOn: [8, 13],
  },

  // Setup Inicial (5 tarefas)
  {
    title: 'Configurar VisaFlow Completamente',
    description: 'Criar processo no VisaFlow, configurar perfil, adicionar informações básicas. Familiarizar-se com a plataforma.',
    phase: 'ELIGIBILITY',
    order: 15,
    dependsOn: [9],
  },
  {
    title: 'Adicionar Colaboradores ao Processo (se houver)',
    description: 'Se tiver advogado, assistente ou revisor, adicionar como colaboradores no VisaFlow com permissões apropriadas.',
    phase: 'ELIGIBILITY',
    order: 16,
    dependsOn: [15],
  },
  {
    title: 'Definir North Star Statement Inicial',
    description: 'Criar declaração principal (tese) do seu caso EB-1A. Deve resumir sua habilidade extraordinária em 1-2 parágrafos.',
    phase: 'ELIGIBILITY',
    order: 17,
    dependsOn: [3, 5],
  },
  {
    title: 'Configurar Notificações e Lembretes',
    description: 'Configurar sistema de notificações no VisaFlow para prazos importantes e tarefas pendentes.',
    phase: 'ELIGIBILITY',
    order: 18,
    dependsOn: [15],
  },
  {
    title: 'Revisar e Aprovar Estratégia Inicial',
    description: 'Fazer revisão final da estratégia antes de avançar para fase de evidências. Confirmar critérios escolhidos e timeline.',
    phase: 'ELIGIBILITY',
    order: 19,
    dependsOn: [5, 9, 17],
  },

  // ============================================
  // PHASE 2: EVIDENCE (Tasks 20-169) - 150 tarefas
  // ============================================

  {
    title: 'Listar Todos os Prêmios Relevantes',
    description: 'Fazer lista completa de todos os prêmios que você possui. Incluir datas, organizações, e contexto.',
    phase: 'EVIDENCE',
    order: 20,
    dependsOn: [19],
  },
  {
    title: 'Verificar Requisitos para Awards',
    description: 'Verificar se seus prêmios atendem requisitos específicos do critério (nacional/internacional, reconhecimento, etc.).',
    phase: 'EVIDENCE',
    order: 21,
    dependsOn: [20],
  },
  {
    title: 'Eliminar Awards Locais/Regionais',
    description: 'Remover da lista qualquer prêmios que seja apenas local ou regional. Focar apenas em reconhecimento nacional/internacional.',
    phase: 'EVIDENCE',
    order: 22,
    dependsOn: [21],
  },
  {
    title: 'Obter Documentos Oficiais de Awards',
    description: 'Coletar certificados, cartas, documentos oficiais que comprovem seus prêmios.',
    phase: 'EVIDENCE',
    order: 23,
    dependsOn: [22],
  },
  {
    title: 'Coletar Estatísticas de Awards',
    description: 'Obter dados estatísticos: número de participantes, taxa de seleção, critérios de elegibilidade, etc.',
    phase: 'EVIDENCE',
    order: 24,
    dependsOn: [22],
  },
  {
    title: 'Documentar Critérios de Seleção para Awards',
    description: 'Coletar informações sobre como você foi selecionado. Quais critérios foram usados? Quem avaliou?',
    phase: 'EVIDENCE',
    order: 25,
    dependsOn: [22],
  },
  {
    title: 'Provar Reconhecimento Internacional de Awards',
    description: 'Documentar que seus prêmios têm reconhecimento além das fronteiras nacionais.',
    phase: 'EVIDENCE',
    order: 26,
    dependsOn: [22],
  },
  {
    title: 'Coletar Screenshots de Páginas Oficiais - Awards',
    description: 'Fazer screenshots de páginas web oficiais mencionando seus prêmios. Incluir URLs visíveis.',
    phase: 'EVIDENCE',
    order: 27,
    dependsOn: [22],
  },
  {
    title: 'Formatar Screenshots com URLs Visíveis - Awards',
    description: 'Editar screenshots para garantir que URLs estejam visíveis e legíveis. Adicionar anotações se necessário.',
    phase: 'EVIDENCE',
    order: 28,
    dependsOn: [27],
  },
  {
    title: 'Traduzir Documentos de Awards (se necessário)',
    description: 'Se documentos não estiverem em inglês, traduzir profissionalmente e certificar traduções.',
    phase: 'EVIDENCE',
    order: 29,
    dependsOn: [27],
  },
  {
    title: 'Criar Tabela Comparativa para Awards',
    description: 'Se aplicável, criar tabela comparando seus prêmios com outros no campo.',
    phase: 'EVIDENCE',
    order: 30,
    dependsOn: [27],
  },
  {
    title: 'Escrever Subseção 1: Proof of Recipient - Awards',
    description: 'Demonstrar que você recebeu o prêmios. Incluir evidências específicas.',
    phase: 'EVIDENCE',
    order: 31,
    dependsOn: [30],
  },
  {
    title: 'Escrever Subseção 2: Proof of Excellence - Awards',
    description: 'Demonstrar que o prêmios reconhece excelência. Explicar critérios e padrões.',
    phase: 'EVIDENCE',
    order: 32,
    dependsOn: [32],
  },
  {
    title: 'Escrever Subseção 3: Proof of Requirements - Awards',
    description: 'Demonstrar que o prêmios não tem limitações geográficas ou temporais.',
    phase: 'EVIDENCE',
    order: 33,
    dependsOn: [33],
  },
  {
    title: 'Escrever Subseção 4: Proof of Recognition - Awards',
    description: 'Demonstrar reconhecimento amplo do prêmios pela comunidade.',
    phase: 'EVIDENCE',
    order: 34,
    dependsOn: [34],
  },

  // --- Awards Complete ---

  {
    title: 'Validar Awards com IA (Claude)',
    description: 'Usar validador automático do VisaFlow para analisar qualidade das subseções e evidências.',
    phase: 'EVIDENCE',
    order: 35,
    dependsOn: [34],
  },
  {
    title: 'Revisar Awards com Checklist',
    description: 'Revisar todas as 4 subseções usando checklist de qualidade. Verificar completude e força.',
    phase: 'EVIDENCE',
    order: 36,
    dependsOn: [36],
  },
  {
    title: 'Obter Feedback de Reviewer para Awards',
    description: 'Se tiver colaborador revisor, solicitar feedback sobre prêmios. Incorporar sugestões.',
    phase: 'EVIDENCE',
    order: 37,
    dependsOn: [37],
  },
  {
    title: 'Listar Todos os Associações Relevantes',
    description: 'Fazer lista completa de todos os associações que você possui. Incluir datas, organizações, e contexto.',
    phase: 'EVIDENCE',
    order: 38,
    dependsOn: [37],
  },
  {
    title: 'Verificar Requisitos para Membership',
    description: 'Verificar se seus associações atendem requisitos específicos do critério (nacional/internacional, reconhecimento, etc.).',
    phase: 'EVIDENCE',
    order: 39,
    dependsOn: [38],
  },
  {
    title: 'Eliminar Membership Locais/Regionais',
    description: 'Remover da lista qualquer associações que seja apenas local ou regional. Focar apenas em reconhecimento nacional/internacional.',
    phase: 'EVIDENCE',
    order: 40,
    dependsOn: [39],
  },
  {
    title: 'Obter Documentos Oficiais de Membership',
    description: 'Coletar certificados, cartas, documentos oficiais que comprovem seus associações.',
    phase: 'EVIDENCE',
    order: 41,
    dependsOn: [40],
  },
  {
    title: 'Coletar Estatísticas de Membership',
    description: 'Obter dados estatísticos: número de participantes, taxa de seleção, critérios de elegibilidade, etc.',
    phase: 'EVIDENCE',
    order: 42,
    dependsOn: [40],
  },
  {
    title: 'Documentar Critérios de Seleção para Membership',
    description: 'Coletar informações sobre como você foi selecionado. Quais critérios foram usados? Quem avaliou?',
    phase: 'EVIDENCE',
    order: 43,
    dependsOn: [40],
  },
  {
    title: 'Provar Reconhecimento Internacional de Membership',
    description: 'Documentar que seus associações têm reconhecimento além das fronteiras nacionais.',
    phase: 'EVIDENCE',
    order: 44,
    dependsOn: [40],
  },
  {
    title: 'Coletar Screenshots de Páginas Oficiais - Membership',
    description: 'Fazer screenshots de páginas web oficiais mencionando seus associações. Incluir URLs visíveis.',
    phase: 'EVIDENCE',
    order: 45,
    dependsOn: [40],
  },
  {
    title: 'Formatar Screenshots com URLs Visíveis - Membership',
    description: 'Editar screenshots para garantir que URLs estejam visíveis e legíveis. Adicionar anotações se necessário.',
    phase: 'EVIDENCE',
    order: 46,
    dependsOn: [45],
  },
  {
    title: 'Traduzir Documentos de Membership (se necessário)',
    description: 'Se documentos não estiverem em inglês, traduzir profissionalmente e certificar traduções.',
    phase: 'EVIDENCE',
    order: 47,
    dependsOn: [45],
  },
  {
    title: 'Criar Tabela Comparativa para Membership',
    description: 'Se aplicável, criar tabela comparando seus associações com outros no campo.',
    phase: 'EVIDENCE',
    order: 48,
    dependsOn: [45],
  },
  {
    title: 'Escrever Subseção 1: Proof of Recipient - Membership',
    description: 'Demonstrar que você recebeu o associações. Incluir evidências específicas.',
    phase: 'EVIDENCE',
    order: 49,
    dependsOn: [48],
  },

  // --- Membership Complete ---

  {
    title: 'Escrever Subseção 2: Proof of Excellence - Membership',
    description: 'Demonstrar que o associações reconhece excelência. Explicar critérios e padrões.',
    phase: 'EVIDENCE',
    order: 50,
    dependsOn: [50],
  },
  {
    title: 'Escrever Subseção 3: Proof of Requirements - Membership',
    description: 'Demonstrar que o associações não tem limitações geográficas ou temporais.',
    phase: 'EVIDENCE',
    order: 51,
    dependsOn: [51],
  },
  {
    title: 'Escrever Subseção 4: Proof of Recognition - Membership',
    description: 'Demonstrar reconhecimento amplo do associações pela comunidade.',
    phase: 'EVIDENCE',
    order: 52,
    dependsOn: [52],
  },
  {
    title: 'Validar Membership com IA (Claude)',
    description: 'Usar validador automático do VisaFlow para analisar qualidade das subseções e evidências.',
    phase: 'EVIDENCE',
    order: 53,
    dependsOn: [52],
  },
  {
    title: 'Revisar Membership com Checklist',
    description: 'Revisar todas as 4 subseções usando checklist de qualidade. Verificar completude e força.',
    phase: 'EVIDENCE',
    order: 54,
    dependsOn: [54],
  },
  {
    title: 'Obter Feedback de Reviewer para Membership',
    description: 'Se tiver colaborador revisor, solicitar feedback sobre associações. Incorporar sugestões.',
    phase: 'EVIDENCE',
    order: 55,
    dependsOn: [55],
  },
  {
    title: 'Listar Todos os Cobertura de Imprensa Relevantes',
    description: 'Fazer lista completa de todos os cobertura de imprensa que você possui. Incluir datas, organizações, e contexto.',
    phase: 'EVIDENCE',
    order: 56,
    dependsOn: [55],
  },
  {
    title: 'Verificar Requisitos para Press',
    description: 'Verificar se seus cobertura de imprensa atendem requisitos específicos do critério (nacional/internacional, reconhecimento, etc.).',
    phase: 'EVIDENCE',
    order: 57,
    dependsOn: [56],
  },
  {
    title: 'Eliminar Press Locais/Regionais',
    description: 'Remover da lista qualquer cobertura de imprensa que seja apenas local ou regional. Focar apenas em reconhecimento nacional/internacional.',
    phase: 'EVIDENCE',
    order: 58,
    dependsOn: [57],
  },
  {
    title: 'Obter Documentos Oficiais de Press',
    description: 'Coletar certificados, cartas, documentos oficiais que comprovem seus cobertura de imprensa.',
    phase: 'EVIDENCE',
    order: 59,
    dependsOn: [58],
  },
  {
    title: 'Coletar Estatísticas de Press',
    description: 'Obter dados estatísticos: número de participantes, taxa de seleção, critérios de elegibilidade, etc.',
    phase: 'EVIDENCE',
    order: 60,
    dependsOn: [58],
  },
  {
    title: 'Documentar Critérios de Seleção para Press',
    description: 'Coletar informações sobre como você foi selecionado. Quais critérios foram usados? Quem avaliou?',
    phase: 'EVIDENCE',
    order: 61,
    dependsOn: [58],
  },
  {
    title: 'Provar Reconhecimento Internacional de Press',
    description: 'Documentar que seus cobertura de imprensa têm reconhecimento além das fronteiras nacionais.',
    phase: 'EVIDENCE',
    order: 62,
    dependsOn: [58],
  },
  {
    title: 'Coletar Screenshots de Páginas Oficiais - Press',
    description: 'Fazer screenshots de páginas web oficiais mencionando seus cobertura de imprensa. Incluir URLs visíveis.',
    phase: 'EVIDENCE',
    order: 63,
    dependsOn: [58],
  },
  {
    title: 'Formatar Screenshots com URLs Visíveis - Press',
    description: 'Editar screenshots para garantir que URLs estejam visíveis e legíveis. Adicionar anotações se necessário.',
    phase: 'EVIDENCE',
    order: 64,
    dependsOn: [63],
  },

  // --- Press Complete ---

  {
    title: 'Traduzir Documentos de Press (se necessário)',
    description: 'Se documentos não estiverem em inglês, traduzir profissionalmente e certificar traduções.',
    phase: 'EVIDENCE',
    order: 65,
    dependsOn: [63],
  },
  {
    title: 'Criar Tabela Comparativa para Press',
    description: 'Se aplicável, criar tabela comparando seus cobertura de imprensa com outros no campo.',
    phase: 'EVIDENCE',
    order: 66,
    dependsOn: [63],
  },
  {
    title: 'Escrever Subseção 1: Proof of Recipient - Press',
    description: 'Demonstrar que você recebeu o cobertura de imprensa. Incluir evidências específicas.',
    phase: 'EVIDENCE',
    order: 67,
    dependsOn: [66],
  },
  {
    title: 'Escrever Subseção 2: Proof of Excellence - Press',
    description: 'Demonstrar que o cobertura de imprensa reconhece excelência. Explicar critérios e padrões.',
    phase: 'EVIDENCE',
    order: 68,
    dependsOn: [68],
  },
  {
    title: 'Escrever Subseção 3: Proof of Requirements - Press',
    description: 'Demonstrar que o cobertura de imprensa não tem limitações geográficas ou temporais.',
    phase: 'EVIDENCE',
    order: 69,
    dependsOn: [69],
  },
  {
    title: 'Escrever Subseção 4: Proof of Recognition - Press',
    description: 'Demonstrar reconhecimento amplo do cobertura de imprensa pela comunidade.',
    phase: 'EVIDENCE',
    order: 70,
    dependsOn: [70],
  },
  {
    title: 'Validar Press com IA (Claude)',
    description: 'Usar validador automático do VisaFlow para analisar qualidade das subseções e evidências.',
    phase: 'EVIDENCE',
    order: 71,
    dependsOn: [70],
  },
  {
    title: 'Revisar Press com Checklist',
    description: 'Revisar todas as 4 subseções usando checklist de qualidade. Verificar completude e força.',
    phase: 'EVIDENCE',
    order: 72,
    dependsOn: [72],
  },
  {
    title: 'Obter Feedback de Reviewer para Press',
    description: 'Se tiver colaborador revisor, solicitar feedback sobre cobertura de imprensa. Incorporar sugestões.',
    phase: 'EVIDENCE',
    order: 73,
    dependsOn: [73],
  },
  {
    title: 'Listar Todos os Judging Work Relevantes',
    description: 'Fazer lista completa de todos os judging work que você possui. Incluir datas, organizações, e contexto.',
    phase: 'EVIDENCE',
    order: 74,
    dependsOn: [73],
  },
  {
    title: 'Verificar Requisitos para Judging',
    description: 'Verificar se seus judging work atendem requisitos específicos do critério (nacional/internacional, reconhecimento, etc.).',
    phase: 'EVIDENCE',
    order: 75,
    dependsOn: [74],
  },
  {
    title: 'Eliminar Judging Locais/Regionais',
    description: 'Remover da lista qualquer judging work que seja apenas local ou regional. Focar apenas em reconhecimento nacional/internacional.',
    phase: 'EVIDENCE',
    order: 76,
    dependsOn: [75],
  },
  {
    title: 'Obter Documentos Oficiais de Judging',
    description: 'Coletar certificados, cartas, documentos oficiais que comprovem seus judging work.',
    phase: 'EVIDENCE',
    order: 77,
    dependsOn: [76],
  },
  {
    title: 'Coletar Estatísticas de Judging',
    description: 'Obter dados estatísticos: número de participantes, taxa de seleção, critérios de elegibilidade, etc.',
    phase: 'EVIDENCE',
    order: 78,
    dependsOn: [76],
  },
  {
    title: 'Documentar Critérios de Seleção para Judging',
    description: 'Coletar informações sobre como você foi selecionado. Quais critérios foram usados? Quem avaliou?',
    phase: 'EVIDENCE',
    order: 79,
    dependsOn: [76],
  },

  // --- Judging Complete ---

  {
    title: 'Provar Reconhecimento Internacional de Judging',
    description: 'Documentar que seus judging work têm reconhecimento além das fronteiras nacionais.',
    phase: 'EVIDENCE',
    order: 80,
    dependsOn: [76],
  },
  {
    title: 'Coletar Screenshots de Páginas Oficiais - Judging',
    description: 'Fazer screenshots de páginas web oficiais mencionando seus judging work. Incluir URLs visíveis.',
    phase: 'EVIDENCE',
    order: 81,
    dependsOn: [76],
  },
  {
    title: 'Formatar Screenshots com URLs Visíveis - Judging',
    description: 'Editar screenshots para garantir que URLs estejam visíveis e legíveis. Adicionar anotações se necessário.',
    phase: 'EVIDENCE',
    order: 82,
    dependsOn: [81],
  },
  {
    title: 'Traduzir Documentos de Judging (se necessário)',
    description: 'Se documentos não estiverem em inglês, traduzir profissionalmente e certificar traduções.',
    phase: 'EVIDENCE',
    order: 83,
    dependsOn: [81],
  },
  {
    title: 'Criar Tabela Comparativa para Judging',
    description: 'Se aplicável, criar tabela comparando seus judging work com outros no campo.',
    phase: 'EVIDENCE',
    order: 84,
    dependsOn: [81],
  },
  {
    title: 'Escrever Subseção 1: Proof of Recipient - Judging',
    description: 'Demonstrar que você recebeu o judging work. Incluir evidências específicas.',
    phase: 'EVIDENCE',
    order: 85,
    dependsOn: [84],
  },
  {
    title: 'Escrever Subseção 2: Proof of Excellence - Judging',
    description: 'Demonstrar que o judging work reconhece excelência. Explicar critérios e padrões.',
    phase: 'EVIDENCE',
    order: 86,
    dependsOn: [86],
  },
  {
    title: 'Escrever Subseção 3: Proof of Requirements - Judging',
    description: 'Demonstrar que o judging work não tem limitações geográficas ou temporais.',
    phase: 'EVIDENCE',
    order: 87,
    dependsOn: [87],
  },
  {
    title: 'Escrever Subseção 4: Proof of Recognition - Judging',
    description: 'Demonstrar reconhecimento amplo do judging work pela comunidade.',
    phase: 'EVIDENCE',
    order: 88,
    dependsOn: [88],
  },
  {
    title: 'Validar Judging com IA (Claude)',
    description: 'Usar validador automático do VisaFlow para analisar qualidade das subseções e evidências.',
    phase: 'EVIDENCE',
    order: 89,
    dependsOn: [88],
  },
  {
    title: 'Revisar Judging com Checklist',
    description: 'Revisar todas as 4 subseções usando checklist de qualidade. Verificar completude e força.',
    phase: 'EVIDENCE',
    order: 90,
    dependsOn: [90],
  },
  {
    title: 'Obter Feedback de Reviewer para Judging',
    description: 'Se tiver colaborador revisor, solicitar feedback sobre judging work. Incorporar sugestões.',
    phase: 'EVIDENCE',
    order: 91,
    dependsOn: [91],
  },
  {
    title: 'Listar Todos os Contribuições Originais Relevantes',
    description: 'Fazer lista completa de todos os contribuições originais que você possui. Incluir datas, organizações, e contexto.',
    phase: 'EVIDENCE',
    order: 92,
    dependsOn: [91],
  },
  {
    title: 'Verificar Requisitos para Original Contributions',
    description: 'Verificar se seus contribuições originais atendem requisitos específicos do critério (nacional/internacional, reconhecimento, etc.).',
    phase: 'EVIDENCE',
    order: 93,
    dependsOn: [92],
  },
  {
    title: 'Eliminar Original Contributions Locais/Regionais',
    description: 'Remover da lista qualquer contribuições originais que seja apenas local ou regional. Focar apenas em reconhecimento nacional/internacional.',
    phase: 'EVIDENCE',
    order: 94,
    dependsOn: [93],
  },

  // --- Original Contributions Complete ---

  {
    title: 'Obter Documentos Oficiais de Original Contributions',
    description: 'Coletar certificados, cartas, documentos oficiais que comprovem seus contribuições originais.',
    phase: 'EVIDENCE',
    order: 95,
    dependsOn: [94],
  },
  {
    title: 'Coletar Estatísticas de Original Contributions',
    description: 'Obter dados estatísticos: número de participantes, taxa de seleção, critérios de elegibilidade, etc.',
    phase: 'EVIDENCE',
    order: 96,
    dependsOn: [94],
  },
  {
    title: 'Documentar Critérios de Seleção para Original Contributions',
    description: 'Coletar informações sobre como você foi selecionado. Quais critérios foram usados? Quem avaliou?',
    phase: 'EVIDENCE',
    order: 97,
    dependsOn: [94],
  },
  {
    title: 'Provar Reconhecimento Internacional de Original Contributions',
    description: 'Documentar que seus contribuições originais têm reconhecimento além das fronteiras nacionais.',
    phase: 'EVIDENCE',
    order: 98,
    dependsOn: [94],
  },
  {
    title: 'Coletar Screenshots de Páginas Oficiais - Original Contributions',
    description: 'Fazer screenshots de páginas web oficiais mencionando seus contribuições originais. Incluir URLs visíveis.',
    phase: 'EVIDENCE',
    order: 99,
    dependsOn: [94],
  },
  {
    title: 'Formatar Screenshots com URLs Visíveis - Original Contributions',
    description: 'Editar screenshots para garantir que URLs estejam visíveis e legíveis. Adicionar anotações se necessário.',
    phase: 'EVIDENCE',
    order: 100,
    dependsOn: [99],
  },
  {
    title: 'Traduzir Documentos de Original Contributions (se necessário)',
    description: 'Se documentos não estiverem em inglês, traduzir profissionalmente e certificar traduções.',
    phase: 'EVIDENCE',
    order: 101,
    dependsOn: [99],
  },
  {
    title: 'Criar Tabela Comparativa para Original Contributions',
    description: 'Se aplicável, criar tabela comparando seus contribuições originais com outros no campo.',
    phase: 'EVIDENCE',
    order: 102,
    dependsOn: [99],
  },
  {
    title: 'Escrever Subseção 1: Proof of Recipient - Original Contributions',
    description: 'Demonstrar que você recebeu o contribuições originais. Incluir evidências específicas.',
    phase: 'EVIDENCE',
    order: 103,
    dependsOn: [102],
  },
  {
    title: 'Escrever Subseção 2: Proof of Excellence - Original Contributions',
    description: 'Demonstrar que o contribuições originais reconhece excelência. Explicar critérios e padrões.',
    phase: 'EVIDENCE',
    order: 104,
    dependsOn: [104],
  },
  {
    title: 'Escrever Subseção 3: Proof of Requirements - Original Contributions',
    description: 'Demonstrar que o contribuições originais não tem limitações geográficas ou temporais.',
    phase: 'EVIDENCE',
    order: 105,
    dependsOn: [105],
  },
  {
    title: 'Escrever Subseção 4: Proof of Recognition - Original Contributions',
    description: 'Demonstrar reconhecimento amplo do contribuições originais pela comunidade.',
    phase: 'EVIDENCE',
    order: 106,
    dependsOn: [106],
  },
  {
    title: 'Validar Original Contributions com IA (Claude)',
    description: 'Usar validador automático do VisaFlow para analisar qualidade das subseções e evidências.',
    phase: 'EVIDENCE',
    order: 107,
    dependsOn: [106],
  },
  {
    title: 'Revisar Original Contributions com Checklist',
    description: 'Revisar todas as 4 subseções usando checklist de qualidade. Verificar completude e força.',
    phase: 'EVIDENCE',
    order: 108,
    dependsOn: [108],
  },
  {
    title: 'Obter Feedback de Reviewer para Original Contributions',
    description: 'Se tiver colaborador revisor, solicitar feedback sobre contribuições originais. Incorporar sugestões.',
    phase: 'EVIDENCE',
    order: 109,
    dependsOn: [109],
  },

  // --- Scholarly Articles Complete ---

  {
    title: 'Listar Todos os Artigos Acadêmicos Relevantes',
    description: 'Fazer lista completa de todos os artigos acadêmicos que você possui. Incluir datas, organizações, e contexto.',
    phase: 'EVIDENCE',
    order: 110,
    dependsOn: [109],
  },
  {
    title: 'Verificar Requisitos para Scholarly Articles',
    description: 'Verificar se seus artigos acadêmicos atendem requisitos específicos do critério (nacional/internacional, reconhecimento, etc.).',
    phase: 'EVIDENCE',
    order: 111,
    dependsOn: [110],
  },
  {
    title: 'Eliminar Scholarly Articles Locais/Regionais',
    description: 'Remover da lista qualquer artigos acadêmicos que seja apenas local ou regional. Focar apenas em reconhecimento nacional/internacional.',
    phase: 'EVIDENCE',
    order: 112,
    dependsOn: [111],
  },
  {
    title: 'Obter Documentos Oficiais de Scholarly Articles',
    description: 'Coletar certificados, cartas, documentos oficiais que comprovem seus artigos acadêmicos.',
    phase: 'EVIDENCE',
    order: 113,
    dependsOn: [112],
  },
  {
    title: 'Coletar Estatísticas de Scholarly Articles',
    description: 'Obter dados estatísticos: número de participantes, taxa de seleção, critérios de elegibilidade, etc.',
    phase: 'EVIDENCE',
    order: 114,
    dependsOn: [112],
  },
  {
    title: 'Documentar Critérios de Seleção para Scholarly Articles',
    description: 'Coletar informações sobre como você foi selecionado. Quais critérios foram usados? Quem avaliou?',
    phase: 'EVIDENCE',
    order: 115,
    dependsOn: [112],
  },
  {
    title: 'Provar Reconhecimento Internacional de Scholarly Articles',
    description: 'Documentar que seus artigos acadêmicos têm reconhecimento além das fronteiras nacionais.',
    phase: 'EVIDENCE',
    order: 116,
    dependsOn: [112],
  },
  {
    title: 'Coletar Screenshots de Páginas Oficiais - Scholarly Articles',
    description: 'Fazer screenshots de páginas web oficiais mencionando seus artigos acadêmicos. Incluir URLs visíveis.',
    phase: 'EVIDENCE',
    order: 117,
    dependsOn: [112],
  },
  {
    title: 'Formatar Screenshots com URLs Visíveis - Scholarly Articles',
    description: 'Editar screenshots para garantir que URLs estejam visíveis e legíveis. Adicionar anotações se necessário.',
    phase: 'EVIDENCE',
    order: 118,
    dependsOn: [117],
  },
  {
    title: 'Traduzir Documentos de Scholarly Articles (se necessário)',
    description: 'Se documentos não estiverem em inglês, traduzir profissionalmente e certificar traduções.',
    phase: 'EVIDENCE',
    order: 119,
    dependsOn: [117],
  },
  {
    title: 'Criar Tabela Comparativa para Scholarly Articles',
    description: 'Se aplicável, criar tabela comparando seus artigos acadêmicos com outros no campo.',
    phase: 'EVIDENCE',
    order: 120,
    dependsOn: [117],
  },
  {
    title: 'Escrever Subseção 1: Proof of Recipient - Scholarly Articles',
    description: 'Demonstrar que você recebeu o artigos acadêmicos. Incluir evidências específicas.',
    phase: 'EVIDENCE',
    order: 121,
    dependsOn: [120],
  },
  {
    title: 'Escrever Subseção 2: Proof of Excellence - Scholarly Articles',
    description: 'Demonstrar que o artigos acadêmicos reconhece excelência. Explicar critérios e padrões.',
    phase: 'EVIDENCE',
    order: 122,
    dependsOn: [122],
  },
  {
    title: 'Escrever Subseção 3: Proof of Requirements - Scholarly Articles',
    description: 'Demonstrar que o artigos acadêmicos não tem limitações geográficas ou temporais.',
    phase: 'EVIDENCE',
    order: 123,
    dependsOn: [123],
  },
  {
    title: 'Escrever Subseção 4: Proof of Recognition - Scholarly Articles',
    description: 'Demonstrar reconhecimento amplo do artigos acadêmicos pela comunidade.',
    phase: 'EVIDENCE',
    order: 124,
    dependsOn: [124],
  },

  // --- Critical Role Complete ---

  {
    title: 'Validar Scholarly Articles com IA (Claude)',
    description: 'Usar validador automático do VisaFlow para analisar qualidade das subseções e evidências.',
    phase: 'EVIDENCE',
    order: 125,
    dependsOn: [124],
  },
  {
    title: 'Revisar Scholarly Articles com Checklist',
    description: 'Revisar todas as 4 subseções usando checklist de qualidade. Verificar completude e força.',
    phase: 'EVIDENCE',
    order: 126,
    dependsOn: [126],
  },
  {
    title: 'Obter Feedback de Reviewer para Scholarly Articles',
    description: 'Se tiver colaborador revisor, solicitar feedback sobre artigos acadêmicos. Incorporar sugestões.',
    phase: 'EVIDENCE',
    order: 127,
    dependsOn: [127],
  },
  {
    title: 'Listar Todos os Papel de Liderança Relevantes',
    description: 'Fazer lista completa de todos os papel de liderança que você possui. Incluir datas, organizações, e contexto.',
    phase: 'EVIDENCE',
    order: 128,
    dependsOn: [127],
  },
  {
    title: 'Verificar Requisitos para Critical Role',
    description: 'Verificar se seus papel de liderança atendem requisitos específicos do critério (nacional/internacional, reconhecimento, etc.).',
    phase: 'EVIDENCE',
    order: 129,
    dependsOn: [128],
  },
  {
    title: 'Eliminar Critical Role Locais/Regionais',
    description: 'Remover da lista qualquer papel de liderança que seja apenas local ou regional. Focar apenas em reconhecimento nacional/internacional.',
    phase: 'EVIDENCE',
    order: 130,
    dependsOn: [129],
  },
  {
    title: 'Obter Documentos Oficiais de Critical Role',
    description: 'Coletar certificados, cartas, documentos oficiais que comprovem seus papel de liderança.',
    phase: 'EVIDENCE',
    order: 131,
    dependsOn: [130],
  },
  {
    title: 'Coletar Estatísticas de Critical Role',
    description: 'Obter dados estatísticos: número de participantes, taxa de seleção, critérios de elegibilidade, etc.',
    phase: 'EVIDENCE',
    order: 132,
    dependsOn: [130],
  },
  {
    title: 'Documentar Critérios de Seleção para Critical Role',
    description: 'Coletar informações sobre como você foi selecionado. Quais critérios foram usados? Quem avaliou?',
    phase: 'EVIDENCE',
    order: 133,
    dependsOn: [130],
  },
  {
    title: 'Provar Reconhecimento Internacional de Critical Role',
    description: 'Documentar que seus papel de liderança têm reconhecimento além das fronteiras nacionais.',
    phase: 'EVIDENCE',
    order: 134,
    dependsOn: [130],
  },
  {
    title: 'Coletar Screenshots de Páginas Oficiais - Critical Role',
    description: 'Fazer screenshots de páginas web oficiais mencionando seus papel de liderança. Incluir URLs visíveis.',
    phase: 'EVIDENCE',
    order: 135,
    dependsOn: [130],
  },
  {
    title: 'Formatar Screenshots com URLs Visíveis - Critical Role',
    description: 'Editar screenshots para garantir que URLs estejam visíveis e legíveis. Adicionar anotações se necessário.',
    phase: 'EVIDENCE',
    order: 136,
    dependsOn: [135],
  },
  {
    title: 'Traduzir Documentos de Critical Role (se necessário)',
    description: 'Se documentos não estiverem em inglês, traduzir profissionalmente e certificar traduções.',
    phase: 'EVIDENCE',
    order: 137,
    dependsOn: [135],
  },
  {
    title: 'Criar Tabela Comparativa para Critical Role',
    description: 'Se aplicável, criar tabela comparando seus papel de liderança com outros no campo.',
    phase: 'EVIDENCE',
    order: 138,
    dependsOn: [135],
  },
  {
    title: 'Escrever Subseção 1: Proof of Recipient - Critical Role',
    description: 'Demonstrar que você recebeu o papel de liderança. Incluir evidências específicas.',
    phase: 'EVIDENCE',
    order: 139,
    dependsOn: [138],
  },

  // --- High Salary Complete ---

  {
    title: 'Escrever Subseção 2: Proof of Excellence - Critical Role',
    description: 'Demonstrar que o papel de liderança reconhece excelência. Explicar critérios e padrões.',
    phase: 'EVIDENCE',
    order: 140,
    dependsOn: [140],
  },
  {
    title: 'Escrever Subseção 3: Proof of Requirements - Critical Role',
    description: 'Demonstrar que o papel de liderança não tem limitações geográficas ou temporais.',
    phase: 'EVIDENCE',
    order: 141,
    dependsOn: [141],
  },
  {
    title: 'Escrever Subseção 4: Proof of Recognition - Critical Role',
    description: 'Demonstrar reconhecimento amplo do papel de liderança pela comunidade.',
    phase: 'EVIDENCE',
    order: 142,
    dependsOn: [142],
  },
  {
    title: 'Validar Critical Role com IA (Claude)',
    description: 'Usar validador automático do VisaFlow para analisar qualidade das subseções e evidências.',
    phase: 'EVIDENCE',
    order: 143,
    dependsOn: [142],
  },
  {
    title: 'Revisar Critical Role com Checklist',
    description: 'Revisar todas as 4 subseções usando checklist de qualidade. Verificar completude e força.',
    phase: 'EVIDENCE',
    order: 144,
    dependsOn: [144],
  },
  {
    title: 'Obter Feedback de Reviewer para Critical Role',
    description: 'Se tiver colaborador revisor, solicitar feedback sobre papel de liderança. Incorporar sugestões.',
    phase: 'EVIDENCE',
    order: 145,
    dependsOn: [145],
  },
  {
    title: 'Listar Todos os Alta Remuneração Relevantes',
    description: 'Fazer lista completa de todos os alta remuneração que você possui. Incluir datas, organizações, e contexto.',
    phase: 'EVIDENCE',
    order: 146,
    dependsOn: [145],
  },
  {
    title: 'Verificar Requisitos para High Salary',
    description: 'Verificar se seus alta remuneração atendem requisitos específicos do critério (nacional/internacional, reconhecimento, etc.).',
    phase: 'EVIDENCE',
    order: 147,
    dependsOn: [146],
  },
  {
    title: 'Eliminar High Salary Locais/Regionais',
    description: 'Remover da lista qualquer alta remuneração que seja apenas local ou regional. Focar apenas em reconhecimento nacional/internacional.',
    phase: 'EVIDENCE',
    order: 148,
    dependsOn: [147],
  },
  {
    title: 'Obter Documentos Oficiais de High Salary',
    description: 'Coletar certificados, cartas, documentos oficiais que comprovem seus alta remuneração.',
    phase: 'EVIDENCE',
    order: 149,
    dependsOn: [148],
  },
  {
    title: 'Coletar Estatísticas de High Salary',
    description: 'Obter dados estatísticos: número de participantes, taxa de seleção, critérios de elegibilidade, etc.',
    phase: 'EVIDENCE',
    order: 150,
    dependsOn: [148],
  },
  {
    title: 'Documentar Critérios de Seleção para High Salary',
    description: 'Coletar informações sobre como você foi selecionado. Quais critérios foram usados? Quem avaliou?',
    phase: 'EVIDENCE',
    order: 151,
    dependsOn: [148],
  },
  {
    title: 'Provar Reconhecimento Internacional de High Salary',
    description: 'Documentar que seus alta remuneração têm reconhecimento além das fronteiras nacionais.',
    phase: 'EVIDENCE',
    order: 152,
    dependsOn: [148],
  },
  {
    title: 'Coletar Screenshots de Páginas Oficiais - High Salary',
    description: 'Fazer screenshots de páginas web oficiais mencionando seus alta remuneração. Incluir URLs visíveis.',
    phase: 'EVIDENCE',
    order: 153,
    dependsOn: [148],
  },
  {
    title: 'Formatar Screenshots com URLs Visíveis - High Salary',
    description: 'Editar screenshots para garantir que URLs estejam visíveis e legíveis. Adicionar anotações se necessário.',
    phase: 'EVIDENCE',
    order: 154,
    dependsOn: [153],
  },

  // --- Exhibitions Complete ---

  {
    title: 'Traduzir Documentos de High Salary (se necessário)',
    description: 'Se documentos não estiverem em inglês, traduzir profissionalmente e certificar traduções.',
    phase: 'EVIDENCE',
    order: 155,
    dependsOn: [153],
  },
  {
    title: 'Criar Tabela Comparativa para High Salary',
    description: 'Se aplicável, criar tabela comparando seus alta remuneração com outros no campo.',
    phase: 'EVIDENCE',
    order: 156,
    dependsOn: [153],
  },
  {
    title: 'Escrever Subseção 1: Proof of Recipient - High Salary',
    description: 'Demonstrar que você recebeu o alta remuneração. Incluir evidências específicas.',
    phase: 'EVIDENCE',
    order: 157,
    dependsOn: [156],
  },
  {
    title: 'Escrever Subseção 2: Proof of Excellence - High Salary',
    description: 'Demonstrar que o alta remuneração reconhece excelência. Explicar critérios e padrões.',
    phase: 'EVIDENCE',
    order: 158,
    dependsOn: [158],
  },
  {
    title: 'Escrever Subseção 3: Proof of Requirements - High Salary',
    description: 'Demonstrar que o alta remuneração não tem limitações geográficas ou temporais.',
    phase: 'EVIDENCE',
    order: 159,
    dependsOn: [159],
  },
  {
    title: 'Escrever Subseção 4: Proof of Recognition - High Salary',
    description: 'Demonstrar reconhecimento amplo do alta remuneração pela comunidade.',
    phase: 'EVIDENCE',
    order: 160,
    dependsOn: [160],
  },
  {
    title: 'Validar High Salary com IA (Claude)',
    description: 'Usar validador automático do VisaFlow para analisar qualidade das subseções e evidências.',
    phase: 'EVIDENCE',
    order: 161,
    dependsOn: [160],
  },
  {
    title: 'Revisar High Salary com Checklist',
    description: 'Revisar todas as 4 subseções usando checklist de qualidade. Verificar completude e força.',
    phase: 'EVIDENCE',
    order: 162,
    dependsOn: [162],
  },
  {
    title: 'Obter Feedback de Reviewer para High Salary',
    description: 'Se tiver colaborador revisor, solicitar feedback sobre alta remuneração. Incorporar sugestões.',
    phase: 'EVIDENCE',
    order: 163,
    dependsOn: [163],
  },
  {
    title: 'Listar Todos os Exibições Artísticas Relevantes',
    description: 'Fazer lista completa de todos os exibições artísticas que você possui. Incluir datas, organizações, e contexto.',
    phase: 'EVIDENCE',
    order: 164,
    dependsOn: [163],
  },
  {
    title: 'Verificar Requisitos para Exhibitions',
    description: 'Verificar se seus exibições artísticas atendem requisitos específicos do critério (nacional/internacional, reconhecimento, etc.).',
    phase: 'EVIDENCE',
    order: 165,
    dependsOn: [164],
  },
  {
    title: 'Eliminar Exhibitions Locais/Regionais',
    description: 'Remover da lista qualquer exibições artísticas que seja apenas local ou regional. Focar apenas em reconhecimento nacional/internacional.',
    phase: 'EVIDENCE',
    order: 166,
    dependsOn: [165],
  },
  {
    title: 'Obter Documentos Oficiais de Exhibitions',
    description: 'Coletar certificados, cartas, documentos oficiais que comprovem seus exibições artísticas.',
    phase: 'EVIDENCE',
    order: 167,
    dependsOn: [166],
  },
  {
    title: 'Coletar Estatísticas de Exhibitions',
    description: 'Obter dados estatísticos: número de participantes, taxa de seleção, critérios de elegibilidade, etc.',
    phase: 'EVIDENCE',
    order: 168,
    dependsOn: [166],
  },
  {
    title: 'Documentar Critérios de Seleção para Exhibitions',
    description: 'Coletar informações sobre como você foi selecionado. Quais critérios foram usados? Quem avaliou?',
    phase: 'EVIDENCE',
    order: 169,
    dependsOn: [166],
  },

  // ============================================
  // PHASE 3: LETTERS (Tasks 170-210) - 41 tarefas
  // ============================================

  {
    title: 'Listar Potenciais Recomendadores (15-20 pessoas)',
    description: 'Fazer lista completa de 15-20 pessoas qualificadas que conheçam seu trabalho: experts reconhecidos, líderes da indústria, acadêmicos.',
    phase: 'LETTERS',
    order: 170,
    dependsOn: [169],
  },
  {
    title: 'Classificar Recomendadores por Relação, Credibilidade e Disponibilidade',
    description: 'Avaliar cada recomendador em três dimensões: relação com você, credibilidade no campo, e disponibilidade para ajudar.',
    phase: 'LETTERS',
    order: 171,
    dependsOn: [170],
  },
  {
    title: 'Verificar Qualificações dos Recomendadores',
    description: 'Pesquisar qualificações de cada recomendador: títulos, posições, publicações, reconhecimentos. Confirmar que são experts reconhecidos.',
    phase: 'LETTERS',
    order: 172,
    dependsOn: [171],
  },
  {
    title: 'Filtrar para 7-10 Recomendadores Finais',
    description: 'Selecionar os 7-10 melhores recomendadores baseado na análise anterior. Priorizar qualidade sobre quantidade.',
    phase: 'LETTERS',
    order: 173,
    dependsOn: [172],
  },
  {
    title: 'Confirmar Disponibilidade Inicial dos Recomendadores',
    description: 'Contactar recomendadores selecionados para confirmar disponibilidade inicial. Explicar brevemente o processo EB-1A.',
    phase: 'LETTERS',
    order: 174,
    dependsOn: [173],
  },
  {
    title: 'Criar Brief Detalhado para Recomendadores (3-5 páginas)',
    description: 'Preparar documento completo com seus achievements, evidências principais, pontos-chave do caso EB-1A, e contexto do processo.',
    phase: 'LETTERS',
    order: 175,
    dependsOn: [174],
  },
  {
    title: 'Compilar Lista de Achievements para Recomendadores',
    description: 'Criar lista organizada de suas realizações mais relevantes, com datas, contexto e impacto. Facilitar escrita das cartas.',
    phase: 'LETTERS',
    order: 176,
    dependsOn: [174],
  },
  {
    title: 'Preparar Exemplos de Cartas Modelo',
    description: 'Criar 2-3 exemplos de cartas de recomendação bem escritas (de casos aprovados) para orientar recomendadores.',
    phase: 'LETTERS',
    order: 177,
    dependsOn: [174],
  },
  {
    title: 'Reunir Evidências de Colaboração com Recomendadores',
    description: 'Coletar documentos que demonstrem colaboração: emails, projetos conjuntos, publicações, eventos, etc.',
    phase: 'LETTERS',
    order: 178,
    dependsOn: [174],
  },
  {
    title: 'Criar Timeline de Solicitação de Cartas',
    description: 'Planejar cronograma de solicitação: quando contactar cada recomendador, prazos esperados, follow-ups necessários.',
    phase: 'LETTERS',
    order: 179,
    dependsOn: [174],
  },
  {
    title: 'Contactar Recomendador 1 e Enviar Materials',
    description: 'Enviar email profissional explicando processo EB-1A, marcar call para explicar detalhes, e enviar brief completo com achievements e exemplos.',
    phase: 'LETTERS',
    order: 180,
    dependsOn: [179],
  },
  {
    title: 'Acompanhar e Receber Carta do Recomendador 1',
    description: 'Fazer follow-up periódico para verificar progresso, receber draft da carta, e revisar qualidade antes de solicitar versão final.',
    phase: 'LETTERS',
    order: 181,
    dependsOn: [180],
  },
  {
    title: 'Finalizar Carta do Recomendador 1',
    description: 'Solicitar revisões se necessário, obter versão final, e confirmar que carta atende padrões de qualidade.',
    phase: 'LETTERS',
    order: 182,
    dependsOn: [181],
  },
  {
    title: 'Contactar Recomendador 2 e Enviar Materials',
    description: 'Enviar email profissional explicando processo EB-1A, marcar call para explicar detalhes, e enviar brief completo com achievements e exemplos.',
    phase: 'LETTERS',
    order: 183,
    dependsOn: [182],
  },
  {
    title: 'Acompanhar e Receber Carta do Recomendador 2',
    description: 'Fazer follow-up periódico para verificar progresso, receber draft da carta, e revisar qualidade antes de solicitar versão final.',
    phase: 'LETTERS',
    order: 184,
    dependsOn: [183],
  },
  {
    title: 'Finalizar Carta do Recomendador 2',
    description: 'Solicitar revisões se necessário, obter versão final, e confirmar que carta atende padrões de qualidade.',
    phase: 'LETTERS',
    order: 185,
    dependsOn: [184],
  },
  {
    title: 'Contactar Recomendador 3 e Enviar Materials',
    description: 'Enviar email profissional explicando processo EB-1A, marcar call para explicar detalhes, e enviar brief completo com achievements e exemplos.',
    phase: 'LETTERS',
    order: 186,
    dependsOn: [185],
  },
  {
    title: 'Acompanhar e Receber Carta do Recomendador 3',
    description: 'Fazer follow-up periódico para verificar progresso, receber draft da carta, e revisar qualidade antes de solicitar versão final.',
    phase: 'LETTERS',
    order: 187,
    dependsOn: [186],
  },
  {
    title: 'Finalizar Carta do Recomendador 3',
    description: 'Solicitar revisões se necessário, obter versão final, e confirmar que carta atende padrões de qualidade.',
    phase: 'LETTERS',
    order: 188,
    dependsOn: [187],
  },
  {
    title: 'Contactar Recomendador 4 e Enviar Materials',
    description: 'Enviar email profissional explicando processo EB-1A, marcar call para explicar detalhes, e enviar brief completo com achievements e exemplos.',
    phase: 'LETTERS',
    order: 189,
    dependsOn: [188],
  },
  {
    title: 'Acompanhar e Receber Carta do Recomendador 4',
    description: 'Fazer follow-up periódico para verificar progresso, receber draft da carta, e revisar qualidade antes de solicitar versão final.',
    phase: 'LETTERS',
    order: 190,
    dependsOn: [189],
  },
  {
    title: 'Finalizar Carta do Recomendador 4',
    description: 'Solicitar revisões se necessário, obter versão final, e confirmar que carta atende padrões de qualidade.',
    phase: 'LETTERS',
    order: 191,
    dependsOn: [190],
  },
  {
    title: 'Contactar Recomendador 5 e Enviar Materials',
    description: 'Enviar email profissional explicando processo EB-1A, marcar call para explicar detalhes, e enviar brief completo com achievements e exemplos.',
    phase: 'LETTERS',
    order: 192,
    dependsOn: [191],
  },
  {
    title: 'Acompanhar e Receber Carta do Recomendador 5',
    description: 'Fazer follow-up periódico para verificar progresso, receber draft da carta, e revisar qualidade antes de solicitar versão final.',
    phase: 'LETTERS',
    order: 193,
    dependsOn: [192],
  },
  {
    title: 'Finalizar Carta do Recomendador 5',
    description: 'Solicitar revisões se necessário, obter versão final, e confirmar que carta atende padrões de qualidade.',
    phase: 'LETTERS',
    order: 194,
    dependsOn: [193],
  },
  {
    title: 'Contactar Recomendador 6 e Enviar Materials',
    description: 'Enviar email profissional explicando processo EB-1A, marcar call para explicar detalhes, e enviar brief completo com achievements e exemplos.',
    phase: 'LETTERS',
    order: 195,
    dependsOn: [194],
  },
  {
    title: 'Acompanhar e Receber Carta do Recomendador 6',
    description: 'Fazer follow-up periódico para verificar progresso, receber draft da carta, e revisar qualidade antes de solicitar versão final.',
    phase: 'LETTERS',
    order: 196,
    dependsOn: [195],
  },
  {
    title: 'Finalizar Carta do Recomendador 6',
    description: 'Solicitar revisões se necessário, obter versão final, e confirmar que carta atende padrões de qualidade.',
    phase: 'LETTERS',
    order: 197,
    dependsOn: [196],
  },
  {
    title: 'Contactar Recomendador 7 e Enviar Materials',
    description: 'Enviar email profissional explicando processo EB-1A, marcar call para explicar detalhes, e enviar brief completo com achievements e exemplos.',
    phase: 'LETTERS',
    order: 198,
    dependsOn: [197],
  },
  {
    title: 'Acompanhar e Receber Carta do Recomendador 7',
    description: 'Fazer follow-up periódico para verificar progresso, receber draft da carta, e revisar qualidade antes de solicitar versão final.',
    phase: 'LETTERS',
    order: 199,
    dependsOn: [198],
  },
  {
    title: 'Finalizar Carta do Recomendador 7',
    description: 'Solicitar revisões se necessário, obter versão final, e confirmar que carta atende padrões de qualidade.',
    phase: 'LETTERS',
    order: 200,
    dependsOn: [199],
  },
  {
    title: 'Revisar Todas as Cartas Recebidas',
    description: 'Fazer revisão completa de todas as cartas. Verificar especificidade, detalhes, e força dos argumentos.',
    phase: 'LETTERS',
    order: 201,
    dependsOn: [200],
  },
  {
    title: 'Verificar Especificidade das Cartas (não genérico)',
    description: 'Garantir que cada carta menciona achievements específicos, projetos concretos, e impacto real. Evitar linguagem genérica.',
    phase: 'LETTERS',
    order: 202,
    dependsOn: [201],
  },
  {
    title: 'Detectar Linguagem de IA nas Cartas',
    description: 'Usar detector de IA do VisaFlow para identificar texto que parece gerado por IA. Solicitar revisão se necessário.',
    phase: 'LETTERS',
    order: 203,
    dependsOn: [202],
  },
  {
    title: 'Solicitar Revisões nas Cartas que Precisam Melhorias',
    description: 'Contactar recomendadores cujas cartas precisam melhorias. Fornecer feedback específico e construtivo.',
    phase: 'LETTERS',
    order: 204,
    dependsOn: [203],
  },
  {
    title: 'Obter Versões Finais de Todas as Cartas',
    description: 'Receber versões finais revisadas de todas as cartas. Confirmar que atendem padrões de qualidade.',
    phase: 'LETTERS',
    order: 205,
    dependsOn: [204],
  },
  {
    title: 'Obter Assinaturas em Todas as Cartas',
    description: 'Coletar assinaturas físicas ou digitais de todos os recomendadores. Garantir que assinaturas são legíveis.',
    phase: 'LETTERS',
    order: 206,
    dependsOn: [205],
  },
  {
    title: 'Coletar CVs de Todos os Recomendadores',
    description: 'Solicitar e receber CVs atualizados de todos os recomendadores para demonstrar suas qualificações.',
    phase: 'LETTERS',
    order: 207,
    dependsOn: [205],
  },
  {
    title: 'Formatar Cartas Uniformemente',
    description: 'Padronizar formatação de todas as cartas: fonte, espaçamento, headers, footers. Criar aparência profissional.',
    phase: 'LETTERS',
    order: 208,
    dependsOn: [207],
  },
  {
    title: 'Organizar Cartas por Ordem de Importância',
    description: 'Ordenar cartas por força e credibilidade do recomendador. Colocar as mais fortes primeiro no pacote.',
    phase: 'LETTERS',
    order: 209,
    dependsOn: [208],
  },
  {
    title: 'Criar Índice de Cartas de Recomendação',
    description: 'Criar índice listando todas as cartas, recomendadores, e suas qualificações. Facilitar navegação do oficial do USCIS.',
    phase: 'LETTERS',
    order: 210,
    dependsOn: [209],
  },



  // ============================================
  // PHASE 4: PETITION (Tasks 211-255) - 45 tarefas
  // ============================================

  {
    title: 'Criar Table of Contents',
    description: 'Criar índice completo do dossiê com todas as seções, critérios, evidências e páginas correspondentes.',
    phase: 'PETITION',
    order: 211,
    dependsOn: [210],
  },
  {
    title: 'Organizar Evidências por Critério',
    description: 'Estruturar todas as evidências agrupadas por critério. Garantir ordem lógica e fácil navegação.',
    phase: 'PETITION',
    order: 212,
    dependsOn: [211],
  },
  {
    title: 'Numerar Todas as Evidências (Exhibit 1-200)',
    description: 'Atribuir números sequenciais a todas as evidências (Exhibit 1, Exhibit 2, etc.). Criar lista numerada completa.',
    phase: 'PETITION',
    order: 213,
    dependsOn: [212],
  },
  {
    title: 'Criar Lista de Evidências Detalhada',
    description: 'Criar lista completa de todas as evidências com números, títulos, datas e localização no dossiê.',
    phase: 'PETITION',
    order: 214,
    dependsOn: [213],
  },
  {
    title: 'Configurar Referências Cruzadas',
    description: 'Garantir que todas as referências a evidências no texto correspondem aos números corretos. Verificar consistência.',
    phase: 'PETITION',
    order: 215,
    dependsOn: [214],
  },
  {
    title: 'Criar Índice de Nomes e Locais',
    description: 'Criar índice alfabético de todos os nomes próprios, organizações e locais mencionados no dossiê.',
    phase: 'PETITION',
    order: 216,
    dependsOn: [215],
  },
  {
    title: 'Configurar Numeração de Páginas',
    description: 'Garantir numeração consistente de páginas em todo o documento. Verificar que números estão corretos.',
    phase: 'PETITION',
    order: 217,
    dependsOn: [216],
  },
  {
    title: 'Adicionar Headers e Footers',
    description: 'Configurar headers e footers profissionais em todas as páginas. Incluir nome do processo e número de página.',
    phase: 'PETITION',
    order: 218,
    dependsOn: [217],
  },
  {
    title: 'Criar Tabs Físicos (se impressão)',
    description: 'Se imprimindo o dossiê, criar tabs físicos para facilitar navegação do oficial do USCIS entre seções.',
    phase: 'PETITION',
    order: 219,
    dependsOn: [218],
  },
  {
    title: 'Fazer Backup Completo do Dossiê',
    description: 'Criar backup completo de todo o dossiê em múltiplos locais (cloud, HD externo, etc.). Garantir segurança dos dados.',
    phase: 'PETITION',
    order: 220,
    dependsOn: [219],
  },
  {
    title: 'Escrever Cover Letter (1 página)',
    description: 'Redigir carta de apresentação profissional resumindo o caso e solicitando aprovação. Máximo 1 página.',
    phase: 'PETITION',
    order: 221,
    dependsOn: [220],
  },
  {
    title: 'Escrever Summary (2 páginas)',
    description: 'Criar resumo executivo de 2 páginas destacando os principais achievements e argumentos do caso.',
    phase: 'PETITION',
    order: 222,
    dependsOn: [221],
  },
  {
    title: 'Escrever Final Merits Statement - Biografia (5-10 páginas)',
    description: 'Redigir seção biográfica detalhada focada em achievements e trajetória profissional. Demonstrar evolução da carreira.',
    phase: 'PETITION',
    order: 223,
    dependsOn: [222],
  },
  {
    title: 'Escrever Final Merits Statement - Achievements (5-10 páginas)',
    description: 'Documentar todas as realizações principais: prêmios, publicações, contribuições, liderança, impacto.',
    phase: 'PETITION',
    order: 224,
    dependsOn: [223],
  },
  {
    title: 'Escrever Final Merits Statement - Impact (3-5 páginas)',
    description: 'Demonstrar impacto significativo no campo: influência, mudanças causadas, reconhecimento pela comunidade.',
    phase: 'PETITION',
    order: 225,
    dependsOn: [224],
  },
  {
    title: 'Escrever Benefits for US - Economic (2 páginas)',
    description: 'Explicar benefícios econômicos que você trará aos EUA: criação de empregos, receita, crescimento econômico.',
    phase: 'PETITION',
    order: 226,
    dependsOn: [225],
  },
  {
    title: 'Escrever Benefits for US - Innovation (2 páginas)',
    description: 'Demonstrar como sua expertise promoverá inovação nos EUA: novas tecnologias, metodologias, avanços científicos.',
    phase: 'PETITION',
    order: 227,
    dependsOn: [226],
  },
  {
    title: 'Escrever Benefits for US - Education (1 página)',
    description: 'Explicar contribuições educacionais: ensino, mentoria, treinamento de profissionais, disseminação de conhecimento.',
    phase: 'PETITION',
    order: 228,
    dependsOn: [227],
  },
  {
    title: 'Escrever Work Plan - Short term (1 página)',
    description: 'Descrever planos de trabalho para os próximos 1-2 anos nos EUA: projetos, colaborações, objetivos específicos.',
    phase: 'PETITION',
    order: 229,
    dependsOn: [228],
  },
  {
    title: 'Escrever Work Plan - Long term (1 página)',
    description: 'Descrever visão de longo prazo (5-10 anos): impacto esperado, legado, contribuições futuras ao campo.',
    phase: 'PETITION',
    order: 230,
    dependsOn: [229],
  },
  {
    title: 'Escrever Conclusion (1 página)',
    description: 'Criar conclusão forte resumindo argumentos principais e reforçando elegibilidade para EB-1A.',
    phase: 'PETITION',
    order: 231,
    dependsOn: [230],
  },
  {
    title: 'Revisar Todas as Seções Narrativas',
    description: 'Fazer revisão completa de todas as seções escritas: consistência, clareza, força dos argumentos.',
    phase: 'PETITION',
    order: 232,
    dependsOn: [231],
  },
  {
    title: 'Validar Conteúdo com IA (Claude)',
    description: 'Usar validador automático do VisaFlow para detectar fraquezas, linguagem genérica, ou práticas suspeitas.',
    phase: 'PETITION',
    order: 233,
    dependsOn: [232],
  },
  {
    title: 'Fazer Revisão Gramatical Completa',
    description: 'Revisar gramática, ortografia, pontuação e estilo em todo o documento. Garantir inglês perfeito.',
    phase: 'PETITION',
    order: 234,
    dependsOn: [233],
  },
  {
    title: 'Obter Revisão Final de Advogado (opcional)',
    description: 'Se tiver advogado, solicitar revisão final profissional antes de finalizar o dossiê.',
    phase: 'PETITION',
    order: 235,
    dependsOn: [234],
  },
  {
    title: 'Validar Completude de Cada Critério',
    description: 'Verificar que cada critério escolhido tem todas as evidências necessárias e 4 subseções completas.',
    phase: 'PETITION',
    order: 236,
    dependsOn: [235],
  },
  {
    title: 'Verificar 4 Subseções Presentes em Cada Critério',
    description: 'Confirmar que cada critério tem as 4 subseções obrigatórias: Recipient, Excellence, Requirements, Recognition.',
    phase: 'PETITION',
    order: 237,
    dependsOn: [236],
  },
  {
    title: 'Verificar Evidências Numeradas Corretamente',
    description: 'Confirmar que todas as evidências têm números (Exhibit X) e estão referenciadas corretamente no texto.',
    phase: 'PETITION',
    order: 238,
    dependsOn: [237],
  },
  {
    title: 'Verificar Referências Cruzadas Funcionam',
    description: 'Testar todas as referências cruzadas: clicar em cada referência e confirmar que leva ao lugar correto.',
    phase: 'PETITION',
    order: 239,
    dependsOn: [238],
  },
  {
    title: 'Detectar Texto Gerado por IA',
    description: 'Usar detector de IA para identificar texto que parece gerado. Substituir por escrita mais natural e específica.',
    phase: 'PETITION',
    order: 240,
    dependsOn: [239],
  },
  {
    title: 'Verificar Práticas Suspeitas',
    description: 'Revisar contra lista de práticas suspeitas (Globee, Stevie, matérias pagas, etc.). Remover ou explicar adequadamente.',
    phase: 'PETITION',
    order: 241,
    dependsOn: [240],
  },
  {
    title: 'Calcular Score de Qualidade Geral',
    description: 'Usar calculadora de score do VisaFlow para obter pontuação geral (0-100) da petição completa.',
    phase: 'PETITION',
    order: 242,
    dependsOn: [241],
  },
  {
    title: 'Comparar com Petição de Referência Aprovada',
    description: 'Comparar estrutura, profundidade e qualidade com petição aprovada de referência. Identificar gaps.',
    phase: 'PETITION',
    order: 243,
    dependsOn: [242],
  },
  {
    title: 'Fazer Checklist Final Completo',
    description: 'Revisar checklist completo de qualidade: todos os itens devem estar marcados antes de aprovar.',
    phase: 'PETITION',
    order: 244,
    dependsOn: [243],
  },
  {
    title: 'Obter Aprovação Final do Dossiê',
    description: 'Fazer revisão final completa e obter aprovação (própria ou de advogado) antes de avançar para filing.',
    phase: 'PETITION',
    order: 245,
    dependsOn: [244],
  },
  {
    title: 'Preencher Formulário I-140',
    description: 'Completar formulário oficial I-140 do USCIS com todas as informações requeridas. Verificar precisão.',
    phase: 'PETITION',
    order: 246,
    dependsOn: [245],
  },
  {
    title: 'Preencher Formulário I-907 (Premium Processing)',
    description: 'Se usando premium processing, preencher formulário I-907 e anexar ao pacote.',
    phase: 'PETITION',
    order: 247,
    dependsOn: [246],
  },
  {
    title: 'Preencher Formulário G-1145 (Notificações Eletrônicas)',
    description: 'Preencher formulário G-1145 para receber notificações eletrônicas sobre o status do caso.',
    phase: 'PETITION',
    order: 248,
    dependsOn: [247],
  },
  {
    title: 'Preparar Cheques e Pagamentos',
    description: 'Preparar cheques ou formas de pagamento para filing fee ($700) e premium processing ($2,500 se aplicável).',
    phase: 'PETITION',
    order: 249,
    dependsOn: [248],
  },
  {
    title: 'Fazer Cópias Completas do Dossiê',
    description: 'Criar cópias completas de todo o pacote para seus registros. Manter cópias em local seguro.',
    phase: 'PETITION',
    order: 250,
    dependsOn: [245],
  },
  {
    title: 'Organizar Ordem de Documentos',
    description: 'Organizar documentos na ordem correta: formulários primeiro, depois evidências por critério, cartas por último.',
    phase: 'PETITION',
    order: 251,
    dependsOn: [250],
  },
  {
    title: 'Criar Package para Envio',
    description: 'Preparar pacote físico completo: documentos organizados, formulários, pagamentos, tudo em ordem.',
    phase: 'PETITION',
    order: 252,
    dependsOn: [251],
  },
  {
    title: 'Verificar Endereço USCIS Correto',
    description: 'Confirmar endereço correto do centro de serviços do USCIS para envio. Verificar se mudou recentemente.',
    phase: 'PETITION',
    order: 253,
    dependsOn: [252],
  },
  {
    title: 'Criar Tracking Sheet',
    description: 'Criar planilha ou documento para rastrear envio, recebimento, e status do caso.',
    phase: 'PETITION',
    order: 254,
    dependsOn: [253],
  },
  {
    title: 'Fazer Backup Digital Final',
    description: 'Criar backup digital final completo de todo o dossiê antes do envio. Armazenar em múltiplos locais.',
    phase: 'PETITION',
    order: 255,
    dependsOn: [254],
  },



  // ============================================
  // PHASE 5: FILING (Tasks 256-288) - 33 tarefas
  // ============================================

  {
    title: 'Imprimir Petição Completa',
    description: 'Imprimir todas as páginas do dossiê em alta qualidade. Verificar que todas as páginas estão legíveis.',
    phase: 'FILING',
    order: 256,
    dependsOn: [255],
  },
  {
    title: 'Organizar Documentos em Ordem',
    description: 'Organizar todos os documentos impressos na ordem correta: formulários, evidências, cartas.',
    phase: 'FILING',
    order: 257,
    dependsOn: [256],
  },
  {
    title: 'Preparar Package de Envio',
    description: 'Colocar documentos organizados em envelope ou caixa apropriada. Adicionar etiquetas e informações de remetente.',
    phase: 'FILING',
    order: 258,
    dependsOn: [257],
  },
  {
    title: 'Enviar Petição via Correio Certificado',
    description: 'Enviar pacote completo para o centro de serviços correto do USCIS via correio certificado com tracking.',
    phase: 'FILING',
    order: 259,
    dependsOn: [258],
  },
  {
    title: 'Confirmar Recebimento pelo USCIS',
    description: 'Monitorar tracking e confirmar que o USCIS recebeu o pacote. Anotar data de recebimento.',
    phase: 'FILING',
    order: 260,
    dependsOn: [259],
  },
  {
    title: 'Registrar Case Number',
    description: 'Quando receber receipt notice, registrar case number (formato LIN-XX-XXX-XXXXX) no sistema de tracking.',
    phase: 'FILING',
    order: 261,
    dependsOn: [260],
  },
  {
    title: 'Monitorar Status Online',
    description: 'Configurar monitoramento do status do caso no site do USCIS. Verificar regularmente por atualizações.',
    phase: 'FILING',
    order: 262,
    dependsOn: [261],
  },
  {
    title: 'Anotar Priority Date',
    description: 'Registrar priority date (data de recebimento) do caso. Esta data é importante para futuros processos.',
    phase: 'FILING',
    order: 263,
    dependsOn: [262],
  },
  {
    title: 'Aguardar Receipt Notice',
    description: 'Aguardar recebimento do I-797C (Receipt Notice) pelo correio. Normalmente chega em 2-4 semanas.',
    phase: 'FILING',
    order: 264,
    dependsOn: [263],
  },
  {
    title: 'Aguardar Aprovação ou RFE',
    description: 'Aguardar decisão do USCIS. Com premium processing: 9-15 dias. Sem premium: 6-12 meses.',
    phase: 'FILING',
    order: 265,
    dependsOn: [264],
  },
  {
    title: 'Se RFE: Preparar Resposta Completa',
    description: 'Se receber Request for Evidence (RFE), preparar resposta completa e detalhada dentro do prazo (87 dias).',
    phase: 'FILING',
    order: 266,
    dependsOn: [265],
  },
  {
    title: 'Se Aprovação: Comemorar! 🎉',
    description: 'Se caso for aprovado, comemorar a conquista! Você recebeu aprovação do I-140 para EB-1A.',
    phase: 'FILING',
    order: 267,
    dependsOn: [266],
  },
  {
    title: 'Receber I-797 Approval Notice',
    description: 'Receber documento oficial I-797 (Approval Notice) pelo correio. Guardar em local seguro.',
    phase: 'FILING',
    order: 268,
    dependsOn: [267],
  },
  {
    title: 'Aguardar NVC Welcome Letter',
    description: 'Aguardar carta de boas-vindas do National Visa Center (NVC). Normalmente chega em 1-2 meses após aprovação.',
    phase: 'FILING',
    order: 269,
    dependsOn: [268],
  },
  {
    title: 'Preencher Formulário DS-260',
    description: 'Preencher formulário DS-260 online no site do NVC com todas as informações pessoais e de histórico.',
    phase: 'FILING',
    order: 270,
    dependsOn: [269],
  },
  {
    title: 'Coletar Civil Documents',
    description: 'Reunir todos os documentos civis necessários: passaporte, certidões, documentos de identidade.',
    phase: 'FILING',
    order: 271,
    dependsOn: [270],
  },
  {
    title: 'Obter Certidões de Nascimento e Casamento',
    description: 'Obter certidões oficiais traduzidas e certificadas de nascimento e casamento (se aplicável).',
    phase: 'FILING',
    order: 272,
    dependsOn: [271],
  },
  {
    title: 'Obter Police Certificates',
    description: 'Obter certidões de antecedentes criminais de todos os países onde viveu por mais de 6 meses desde os 16 anos.',
    phase: 'FILING',
    order: 273,
    dependsOn: [272],
  },
  {
    title: 'Enviar Documentos ao NVC',
    description: 'Enviar todos os documentos civis ao NVC via portal online ou correio conforme instruções.',
    phase: 'FILING',
    order: 274,
    dependsOn: [273],
  },
  {
    title: 'Aguardar Data de Entrevista',
    description: 'Aguardar agendamento da entrevista no consulado. NVC notificará quando documentos forem aprovados.',
    phase: 'FILING',
    order: 275,
    dependsOn: [274],
  },
  {
    title: 'Agendar Exame Médico',
    description: 'Agendar exame médico em clínica aprovada pelo consulado. Fazer antes da entrevista (normalmente 1-2 semanas antes).',
    phase: 'FILING',
    order: 276,
    dependsOn: [275],
  },
  {
    title: 'Fazer Exame Médico em Clínica Aprovada',
    description: 'Realizar exame médico completo incluindo vacinas necessárias. Receber envelope selado para entregar na entrevista.',
    phase: 'FILING',
    order: 277,
    dependsOn: [276],
  },
  {
    title: 'Reunir Documentos Originais',
    description: 'Reunir todos os documentos originais que serão necessários na entrevista: passaporte, certidões, fotos, etc.',
    phase: 'FILING',
    order: 278,
    dependsOn: [277],
  },
  {
    title: 'Estudar Possíveis Perguntas da Entrevista',
    description: 'Preparar-se para perguntas comuns sobre seu caso EB-1A, trabalho, planos nos EUA, etc.',
    phase: 'FILING',
    order: 279,
    dependsOn: [278],
  },
  {
    title: 'Preparar Documentos de Suporte para Entrevista',
    description: 'Organizar documentos adicionais que podem ser úteis: cópias do dossiê, evidências atualizadas, etc.',
    phase: 'FILING',
    order: 280,
    dependsOn: [279],
  },
  {
    title: 'Comparecer à Entrevista no Consulado',
    description: 'Comparecer à entrevista no consulado na data e hora agendadas. Levar todos os documentos originais.',
    phase: 'FILING',
    order: 281,
    dependsOn: [280],
  },
  {
    title: 'Aguardar Decisão Após Entrevista',
    description: 'Aguardar decisão do oficial consular. Pode ser aprovação imediata, aprovação administrativa, ou solicitação de documentos adicionais.',
    phase: 'FILING',
    order: 282,
    dependsOn: [281],
  },
  {
    title: 'Receber Passaporte com Visto',
    description: 'Receber passaporte com visto EB-1A colado. Visto é válido por 6 meses para entrada nos EUA.',
    phase: 'FILING',
    order: 283,
    dependsOn: [282],
  },
  {
    title: 'Planejar Entrada nos EUA',
    description: 'Planejar viagem de entrada nos EUA dentro da validade do visto. Escolher porto de entrada apropriado.',
    phase: 'FILING',
    order: 284,
    dependsOn: [283],
  },
  {
    title: 'Entrar nos EUA e Virar LPR! 🎉',
    description: 'Entrar nos EUA através do porto de entrada designado. Oficial de imigração carimbará passaporte e você se tornará Legal Permanent Resident (LPR)!',
    phase: 'FILING',
    order: 285,
    dependsOn: [284],
  },
  {
    title: 'Aguardar Recebimento do SSN Card',
    description: 'Aguardar recebimento do Social Security Number (SSN) card pelo correio. Normalmente chega em 2-3 semanas após entrada.',
    phase: 'FILING',
    order: 286,
    dependsOn: [285],
  },
  {
    title: 'Aguardar Recebimento do Green Card',
    description: 'Aguardar recebimento do Green Card físico pelo correio. Normalmente chega em 90-120 dias após entrada.',
    phase: 'FILING',
    order: 287,
    dependsOn: [286],
  },
  {
    title: 'Atualizar Documentos com Status de LPR',
    description: 'Atualizar documentos pessoais, contas bancárias, empregador, etc. com seu novo status de Legal Permanent Resident.',
    phase: 'FILING',
    order: 288,
    dependsOn: [287],
  },



]; // Indexes of tasks this depends on

/**
 * Get default tasks for a specific phase
 */
export function getTasksByPhase(phase: 'ELIGIBILITY' | 'EVIDENCE' | 'LETTERS' | 'PETITION' | 'FILING'): DefaultTask[] {
  return DEFAULT_TASKS.filter(task => task.phase === phase);
}

/**
 * Get all default tasks
 */
export function getAllDefaultTasks(): DefaultTask[] {
  return DEFAULT_TASKS;
}
